version: '3'

services:

  openmu-startup:
    build:
      context: ../../src
      dockerfile: Startup/Dockerfile
    restart: "no"
    ports:
      - "192.168.4.71:8080:8080"

  database:
    ports:
      - "192.168.4.71:5432:5432"
