version: '3'

services:
  nginx-80:
    image: nginx:alpine
    container_name: nginx-80
    ports:
      - "192.168.4.71:80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./logs:/logs:ro
    depends_on:
      - openmu-startup

  openmu-startup:
    image: openmu
    container_name: openmu-startup
    user: "0:0"  # Start as root to fix permissions, entrypoint will switch to app user
    ports:
      - "192.168.4.71:8080:8080"
      - "192.168.4.71:55901:55901"
      - "192.168.4.71:55902:55902"
      - "192.168.4.71:55903:55903"
      - "192.168.4.71:55904:55904"
      - "192.168.4.71:55905:55905"
      - "192.168.4.71:55906:55906"
      - "192.168.4.71:44405:44405"
      - "192.168.4.71:44406:44406"
      - "192.168.4.71:55980:55980"
    environment:
      DB_HOST: database
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      RESOLVE_IP: "192.168.4.71"
      LOGS_PATH: "/logs"
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./logs:/logs
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16-alpine
    container_name: database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: openmu
      POSTGRES_USER: postgres
    ports:
      - "192.168.4.71:5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data #store data on volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  dbdata: